"""Add phase 4 metrics to models

Revision ID: 0fb21c2a96bb
Revises: 40b892d02841
Create Date: 2026-01-24 00:08:00.146806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb21c2a96bb'
down_revision: Union[str, Sequence[str], None] = '40b892d02841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_notes', sa.Column('mood', sa.String(length=50), nullable=True))
    op.add_column('daily_notes', sa.Column('highlight', sa.String(length=255), nullable=True))
    op.add_column('daily_notes', sa.Column('lowlight', sa.String(length=255), nullable=True))
    op.add_column('daily_notes', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('learning_sessions', sa.Column('resource_type', sa.String(length=50), nullable=True))
    op.add_column('learning_sessions', sa.Column('resource_name', sa.String(length=255), nullable=True))
    op.add_column('learning_sessions', sa.Column('takeaways', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_sessions', 'takeaways')
    op.drop_column('learning_sessions', 'resource_name')
    op.drop_column('learning_sessions', 'resource_type')
    op.drop_column('daily_notes', 'tags')
    op.drop_column('daily_notes', 'lowlight')
    op.drop_column('daily_notes', 'highlight')
    op.drop_column('daily_notes', 'mood')
    # ### end Alembic commands ###
