"""Add difficulty column

Revision ID: 2bd1425f11f2
Revises: 0fb21c2a96bb
Create Date: 2026-01-24 09:37:27.167376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd1425f11f2'
down_revision: Union[str, Sequence[str], None] = '0fb21c2a96bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('difficulty', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'difficulty')
    # ### end Alembic commands ###
