"""Add ai_personality to User

Revision ID: 4a31fef328bf
Revises: 8da0e7c8f8f1
Create Date: 2026-01-24 14:34:58.897041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a31fef328bf'
down_revision: Union[str, Sequence[str], None] = '8da0e7c8f8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
