"""Add currency column to expenses

Revision ID: d571880c6a67
Revises: cd76d11ef50c
Create Date: 2026-01-23 23:22:03.540043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd571880c6a67'
down_revision: Union[str, Sequence[str], None] = 'cd76d11ef50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('currency', sa.String(length=3), nullable=False, server_default='NGN'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'currency')
    # ### end Alembic commands ###
